### ISSUE TITLE
Robust error handling

### ISSUE THREAD

**Issue by lance** [keycloak/keycloak-nodejs-auth-utils#15]
As discussed [here](https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/9#discussion-diff-62557714), the error handling for this module is perhaps non-optimal.

**Comment by arconsis** [comment]
+1 I also came along with the invalid-token-issue. 
Don't know if https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/21 is obsolete then.

**Comment by abstractj** [comment]
@lance fyi moved to https://issues.jboss.org/browse/KEYCLOAK-3112
