### ISSUE TITLE
Change all occurrences from 'client-id' to 'resource'

### ISSUE THREAD

**Issue by helio-frota** [keycloak/keycloak-nodejs-auth-utils#25]
According the docs: 

> resource
> The client-id of the application. Each application has a client-id that is used to identify the application. This is REQUIRED.

https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/java/java-adapter-config.html

I'm not sure but I think this will solve https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/22

Occurrences found in code and keycloak.json files.

**Comment by lance** [comment]
I think this is my doing. I will fix...

**Comment by helio-frota** [comment]
@lance thanks !
